### PR TITLE
fix/170v2: add filter to delay post saving.

### LINKED ISSUE #170: Save is executed too fast for gallery
### Describe the bug

I have a site with old galleries that I wanted to convert to Gutenberg blocks. When clicking the Convert to blocks button in the admin it worked, but running this script it failed loading the images. After a lot of testing I found out that the save function is called directly and not giving the Gutenberg script enough time to modify all the images / content.

Adding the timeout around the save function fixed it for me:
https://github.com/10up/convert-to-blocks/blob/develop/assets/js/editor/editor.js#L69

```
setTimeout((function(){
client.save();
}),6000)
```

Takes more time, but better results for me.

### Steps to Reproduce

1. Add a gallery with multiple images in the old editor
2. Convert the post with the convert-to-blocks script
3. Images show up without a src

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

Latest Wordpress, local, with Bedrock
Also tried without Bedrock.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

Closes #170 

### How to test the Change

1. Activate classic editor.
2. Create 2 posts with gallery and add `heading`. (Just to test if the PR works as expected to transform other elements to blocks).
3. Disable the classic editor.
4. Run the following: `wp convert-to-blocks start --post_type=post`
5. Open the URL displayed in the terminal.
6. It will start converting blocks in both the posts.
7. Wait until terminal shows the message: "Migration finished successfully."
8. Open both the posts and reload the page to verify if the transformed blocks are visible as expected.

### Changelog Entry

> Fixed - issue with saving post before the convert to blocks transform completed.

### Credits

Props @mdesplenter, @Sidsector9 @dsawardekar 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: includes/ConvertToBlocks/MigrationAgent.php [hunk 1]
```diff
@@ -24,12 +24,18 @@ public function register() {
...
+		$post_id         = $posts_to_update[ $cursor ] ?? 0;
+
 		wp_localize_script(
 			'convert_to_blocks_editor',
 			'convert_to_blocks_agent',
 			[
 				'agent' => [
-					'next' => $this->next(),
+					'next'       => $this->next(),
+					'save_delay' => apply_filters( 'convert_to_blocks_save_delay', 500, $post_id )
```
Comment (dsawardekar) [inline includes/ConvertToBlocks/MigrationAgent.php]: @Sidsector9 Lets change this to 0, or there is no delay to match the legacy behaviour. For context, 500 ms adds hours to a migration that has 100k posts.

File: assets/js/editor/editor.js [hunk 2]
```diff
@@ -66,7 +66,9 @@ class ConvertToBlocksEditorSupport {
 						return null;
 					}
 
-					client.save();
+					setTimeout(() => {
+						client.save();
+					}, config.agent.save_delay);
```
Comment (dsawardekar) [inline assets/js/editor/editor.js]: @Sidsector9 Lets add a JS fallback to 0 in case the BE doesn't send this var. Sometimes this happens on large migrations when the BE stalls. If `save_delay` is 0, then call save directly instead of using the `setTimeout`.

**Review by dsawardekar — CHANGES_REQUESTED** [review]
Looks close, needs a couple of changes.

**Review by dsawardekar — APPROVED** [review]
